### ISSUE TITLE
Add LETKF yaml for 2024052700 MPAS case 

### ISSUE THREAD

**Issue by SamuelDegelia-NOAA** [NOAA-EMC/RDASApp#124]
I am planning to add a yaml file to run LETKF for the 2024052700 MPAS case. I will also likely rename the current `sonde_singeob_airTemperature_mpasjedi.yaml` to have separate EnVar and LETKF yaml files.

**Comment by SamuelDegelia-NOAA** [comment]
A couple of semi-related questions for @guoqing-noaa in the interest of cleaning up some of the `rrfs-test` directory. 

1. Do we still need `ush/init.sh` or has that functionality been fully covered by `rrfs-test/scripts/link_mpasjedi_expr.sh`? 
2. Do we need `rrfs-test/scripts/templates/mpasjedi_expr/run_jedi.sh` given the presence of `rrfs-test/scripts/templates/run_mpasjedi_template`?

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Thanks for working on this!

To answer the questions:
> 1. Do we still need `ush/init.sh` or has that functionality been fully covered by `rrfs-test/scripts/link_mpasjedi_expr.sh`?

`init.sh` in `link_mpasjedi_expr.sh` is a safeguard (or redundant backup) to make sure the fix/ directory is initialized.
If your LETKF experiment uses a separate script, it is still best to include "init.sh" just in case.

> 2. Do we need `rrfs-test/scripts/templates/mpasjedi_expr/run_jedi.sh` given the presence of `rrfs-test/scripts/templates/run_mpasjedi_template`?

Yes, we need both of them at least now because `run_jedi.sh` and `run_mpasjedi_template` have different logic.
