### ISSUE TITLE
A problem when running the MPAS-JEDI case with the recent variable name changes

### ISSUE THREAD

**Issue by HuiLiu-NOAA** [NOAA-EMC/RDASApp#226]
I cloned the latest RDAS with the recent variable name changes. I also updated the geovals.yaml and obsop_name_map.yaml accordingly.  When I ran the 3D-enVar case at 2022052700 case and got an error:

 0: OOPS_TRACE[0] Variational Assimilation Type=3D-Var
 0: OOPS_TRACE[0] CostFactory::create found cost function type
 0: OOPS_TRACE[0] Geometry<MODEL>::Geometry starting
 0: OOPS_TRACE[0] ========= Geometry::Geometry step 1 ==========
 0: ==> create geom
 0: Abort(437918234) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 437918234) - process 0

Any idea about this error or anyone have successfully run the case?

The full error log is in /scratch1/NCEPDEV/fv3-cam/Hui.Liu/testmpas/log.ttt

**Comment by SamuelDegelia-NOAA** [comment]
Hui, I tried copying your run directory and running mpas-jedi with `ttt.yaml` and found the following error: 

```
ERROR: No stream matching static exists in call to MPAS_stream_mgr_set_property().
ERROR: ********************************************************************************
ERROR:  Error: Stream 'static' was not defined in the Registry.xml file as
ERROR:         an immutable stream. Immutable streams may only be defined in the Registry.xml
ERROR:         file for a core.
ERROR: ********************************************************************************
CRITICAL ERROR: xml stream parser failed: ./streams.atmosphere_15km
Logging complete.  Closing file at 2024/11/18 16:32:24
```

It looks like the immutable stream `static` changed names to `invariant` in a recent update to MPAS in RDASApp. So your `streams.atmosphere_15km` needs to be modified for that purpose. After doing that, I got an error in `VEGPARM.TBL` which also has been updated with a new version of MPAS. Replacing that with the latest version in RDASApp gets me further and I now get an error related to the `SfcCorrected` obs operator. 

I think it might be easier to run your tests using the new MPAS-JEDI case in RDASApp instead of the older case you are trying to run with. You can try running in `RDASApp/expr/mpas_2024052700`, where all of the input files should already be updated for the latest versions of MPAS and MPAS-JEDI.

**Comment by HuiLiu-NOAA** [comment]
Thanks @SamuelDegelia-NOAA for the help! 
I will try the new setup.

**Comment by HuiLiu-NOAA** [comment]
hi, Sam,

  I noticed that the 2nd ombg should be removed from the
 rrfs_mpasjedi_2024052700_Ens3Dvar.yaml
in the RDASApp/expr/mpas_2024052700/

hui

**Comment by SamuelDegelia-NOAA** [comment]
@HuiLiu-NOAA Thank you for catching this. I just tested it and it luckily it looks like the extra `ombg` does not change the analysis or the o-b data output to the hofx files. But it should still be removed. I'll add a quick hotfix to remove this.

**Comment by guoqing-noaa** [comment]
> @HuiLiu-NOAA Thank you for catching this. I just tested it and it luckily it looks like the extra `ombg` does not change the analysis or the o-b data output to the hofx files. But it should still be removed. I'll add a quick hotfix to remove this.

Yes, the YAML function will just overwrite the first ombg diagnostic dictionary with the second specification internally.
