### ISSUE TITLE
Support RDASApp on Jet

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/RDASApp#55]
GSL people use Jet a lot. It will be great if we can run RDASapp on Jet.

Do we have any plans to support RDASApp on Jet?

-----for reference---
`wget https://bin.ssec.wisc.edu/pub/s4/CRTM/file/crtm_coefficients_2.4.1_skylab_4.0.tar.gz ` 
(this is needed by the current RDASapp)

**Comment by delippi** [comment]
I don't see why not. I can see if I can add support for that.

**Comment by SamuelDegelia-NOAA** [comment]
@delippi I currently do not have access to Jet but feel free to copy all of the staged data from my directories on either Hera or Orion.

**Comment by ShunLiu-NOAA** [comment]
@guoqing-noaa Is it also helpful if you can involve staging data on Jet. Eventually, we are going to co-host RDASApp with GSL on Hera, Orion, WCOSS and Jet.

**Comment by hu5970** [comment]
We do not have problem to compile RDASApp on Jet. But need to prepare test data.

**Comment by delippi** [comment]
> @guoqing-noaa Is it also helpful if you can involve staging data on Jet. Eventually, we are going to co-host RDASApp with GSL on Hera, Orion, WCOSS and Jet.

That is a good point. @guoqing-noaa, I seem to be having trouble doing anything on Jet at the moment. You could copy Sam's staged data from Hera
`/scratch1/NCEPDEV/da/Samuel.Degelia/RRFS`
and my staged data for GSI case from Hera
`/scratch2/NCEPDEV/fv3-cam/Donald.E.Lippi/RRFSv2/staged-data/gsi_2022052619`

When we have the role accounts in the near future, all of this data will just need to go in one location. And I'll try to figure out what is going on with my account on Jet.

**Comment by guoqing-noaa** [comment]
Thanks all for the inputs! I can copy those testing data to a directory under GSL's role account role.rtrr.

@hu5970 We haven't have `modulefiles/RDAS/jet.intel.lua` yet. Did you make one? If you, could you commit them back to the repo? Thanks!

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Could you allow global read access to all files under `/scratch1/NCEPDEV/da/Samuel.Degelia/RRFS`?
I cannot read some files under this directory and this stopped my coping from Hera to Jet. Thanks!

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa Could you try again now? Not sure why this issue keeps occurring.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA Let me try it again. 

This may not be related: I met similar issues before. In my situation,  it was caused by "scp" between HPCS. When I used "rsync", it worked better.

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA It worked now. Thanks!

**Comment by guoqing-noaa** [comment]
@SamuelDegelia-NOAA 

What are the differences between `RDASAPP_TESTDATA `and `RDAS_RRFS_DATA_ROOT`? 
Do we need both?

```
setenv("RDASAPP_TESTDATA","/scratch1/NCEPDEV/da/Cory.R.Martin/CI/RDASApp/data")
setenv("RDAS_RRFS_DATA_ROOT", "/scratch1/NCEPDEV/da/Samuel.Degelia/RRFS")

```

**Comment by SamuelDegelia-NOAA** [comment]
@guoqing-noaa These env variable names should probably be changed in a future PR. `RDASAPP_TESTDATA` is used in `RDASApp/bundle/CMakeLists.txt` and points to some of the general staged data for ioda, ufo, fv3-jedi, mpas-jedi, and crtm. This variable name was just left over from how GDASApp handles their test data (`GDASAPP_TESTDATA`). 

`RRFS_TEST_DATA` is instead used in `RDASApp/rrfs-test/CMakeLists.txt` and is just the path to the staged data unique for RDASApp like our fv3-jedi and mpas-jedi test cases. In the future we should probably change `RDASAPP_TESTDATA` to something like `JEDI_TEST_DATA` since it is the more general data.

**Comment by delippi** [comment]
@guoqing-noaa, thanks for getting this setup [PR#60](https://github.com/NOAA-EMC/RDASApp/pull/60). Have you tried following the wiki? There is a convenient tool (`RDASApp/rrfs-test/scripts/setup_experiment.sh`) that I wrote to really streamline setting up your experiments. I highly recommend using this script. It will get EMC and GSL on the same page and hopefully solve some of the problems for people just getting started. I just submitted a PR with changes but didn't thoroughly test since I'm not sure if I have accounts to run on Jet. This is the relevant [wiki](https://github.com/NOAA-EMC/RDASApp/wiki/Running-FV3%E2%80%90JEDI-Hofx-Validation)

**Comment by delippi** [comment]
Oops, I forgot to mention the [PR#61](https://github.com/NOAA-EMC/RDASApp/pull/61) that I just opened and would like for you to review

**Comment by guoqing-noaa** [comment]
Thanks, @delippi

**Comment by guoqing-noaa** [comment]
Close this old ticket. If we have issues on Jet, we can open a new issue.
